### ISSUE TITLE
Issues when Javascript is disabled

### ISSUE THREAD

**Issue by michaelsw95** [travisneilson/DevTipsShowWebsite#3]
Side menu has no CSS fall back so when JavaScript is disabled, (commonly in Internet Explorer due to that little pop it does) the user cannot open the menu. Also the sign up seems not available when JavaScript is disabled, however the user is not notified that it does not work…

**Comment by travisneilson** [comment]
Thanks for the heads up. Do you browse w/o JS a lot?

**Comment by michaelsw95** [comment]
No no never! But I wish I could say the same for people who view websites I design. I've gotten into a habit of testing everything I make with JavaScript off. Depends on the demographic of people you are making the site for, less computer literate people often turn off scripts because they think it's dangerous or malicious.

**Comment by travisneilson** [comment]
Ah, this is interesting. Thanks for the consideration :)
